### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by ghost** [naice/MagicMirrorWIN#1]
Hallo Jens,
sobald ich deine App ausführe, kriege ich eine Ausnahme vom Typ "System.UnauthorizedAccessException" und zwar bei der Zeile: await recognizer.ContinuousRecognitionSession.StartAsync();
MainViewModel.cs Zeilennummer: 215.

Hast du vlt eine Ahnung oder ein Tip voran das liegen könnte? Leider ist die Fehlerbeschreibung nicht wirklich hilfreich.

**Comment by naice** [comment]
Hast du ein neues Projekt gemacht und den Code kopiert?
gerrus notifications@github.com schrieb am Mi., 6. Juli 2016 um 11:17:

**Comment by ghost** [comment]
Ne, hab über github "geklont".
Bin übrigens immer noch nicht weiter."Zugriff verweigert" mehr steht da nicht.. Mikrofon-Zugriff ist aber erlaubt in der Einstellungen oder muss man da noch irgendwo anderes etwas erlauben?

**Comment by naice** [comment]
Im Manifest muss das Recht angefordert werden und das Recht muss auch
erteilt werden. Was anderes kann ich mir nicht so recht vorstellen, die
Fehler Beschreibung ist auch suboptimal... aber typisch ;-)
gerrus notifications@github.com schrieb am Do., 7. Juli 2016 um 11:34:
