### ISSUE TITLE
Displayed Time

### ISSUE THREAD

**Issue by gzformula** [naice/MagicMirrorWIN#2]
I'm not sure why but when I run the master (or my version) the time display is constantly updating to increased times very rapidly. The ntp client is returning the correct time, but somewhere along the way (I think with the offset) it gets bigger and bigger so in a matter of seconds the displayed time is nowhere near what it should be.

**Comment by naice** [comment]
Yep, it was for debugging, inside the getter of DateTimeFactory. Just
comment the addition out.
Gary Gerard notifications@github.com schrieb am Sa., 9. Juli 2016 um
18:25:
